# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de categoria', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del producto', max_length=30)),
                ('cantidad', models.FloatField(default=0, help_text='cantidad disponible')),
                ('medida', models.CharField(choices=[('Lts', 'Lts'), ('Kgs', 'Kgs'), ('Unds', 'Unds'), ('Mts', 'Mts')], help_text='unidad de medida', max_length=15)),
                ('minimo', models.FloatField(default=0, help_text='cantidad minima aceptable')),
                ('categoria', models.ForeignKey(help_text='Categoria del producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.Categoria')),
            ],
        ),
    ]
