# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(help_text='cantidad disponible', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo',
            field=models.FloatField(help_text='cantidad minima aceptable'),
        ),
    ]
