# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='nombre de categoria', max_length=30, unique=True),
        ),
    ]
