# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20171109_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eliminable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.Categoria'),
        ),
    ]
