# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20171012_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=0, help_text='cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria del producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo',
            field=models.FloatField(default=0, help_text='cantidad minima aceptable'),
        ),
    ]
