# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20171012_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_transito',
            field=models.FloatField(default=0, help_text='cantidad en transito'),
        ),
    ]
