# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_cantidad_transito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_transito',
        ),
    ]
