# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(help_text='Rif/CI del cliente', max_length=15)),
                ('nombre', models.CharField(help_text='Nomrbe del cliente', max_length=30)),
                ('telefono', models.CharField(help_text='Telefono del cliente', max_length=15, null=True)),
                ('direccion', models.CharField(help_text='Direccion del cliente', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='cantidad de salida')),
                ('fecha', models.DateField(help_text='Fecha de la compra', null=True)),
                ('producto', models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='codigo de la salida', max_length=30, unique=True)),
                ('total', models.FloatField(default=0, help_text='Monto total de la salida')),
                ('fecha', models.DateField(help_text='Fecha de la salida')),
                ('cliente', models.ForeignKey(help_text='cliente de la salida', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='salidas.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='salida',
            field=models.ForeignKey(help_text='salida a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='salidas.Salida'),
        ),
    ]
