# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nomrbe de la dependencia', max_length=30)),
                ('telefono', models.CharField(help_text='Telefono de la dependencia', max_length=15, null=True)),
                ('direccion', models.CharField(help_text='Direccion de la dependencia', max_length=80, null=True)),
                ('descripcion', models.CharField(help_text='Descripcion breve de la dependencia', max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='salida',
            name='dependencia',
            field=models.ForeignKey(default=0, help_text='cliente de la salida', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='salidas.Dependencia'),
        ),
    ]
