# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del usuario', max_length=20)),
                ('apellido', models.CharField(help_text='apellido del usuario', max_length=20)),
                ('direccion', models.CharField(help_text='direccion del usuario', max_length=80, null=True)),
                ('telefono', models.CharField(help_text='telefono del usuario', max_length=15, null=True)),
                ('pregunta', models.CharField(help_text='pregunta de seguridad', max_length=60)),
                ('respuesta', models.CharField(help_text='respuesta de seguridad', max_length=60)),
                ('cargo', models.CharField(help_text='cargo del usuario', max_length=15, null=True)),
                ('user', models.OneToOneField(help_text='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
