# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 10:16
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='codigo de la compra', max_length=32, unique=True)),
                ('total', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto total de la compra', max_digits=16, null=True)),
                ('fecha', models.DateField(help_text='Fecha de la compra')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='cantidad de entrada')),
                ('fecha', models.DateField(help_text='Fecha de la venta', null=True)),
                ('precio', models.DecimalField(decimal_places=8, help_text='Precio unitario del producto', max_digits=16)),
                ('cantidad_procesada', models.FloatField(default=0, help_text='cantidad de procesada')),
                ('compra', models.ForeignKey(help_text='compra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.Compra')),
                ('producto', models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(help_text='rif del proveedor', max_length=15)),
                ('nombre', models.CharField(help_text='nombre del proveedor', max_length=30)),
                ('telefono', models.CharField(help_text='telefono del proveedor', max_length=15, null=True)),
                ('direccion', models.CharField(help_text='direccion del proveedor', max_length=80, null=True)),
                ('ultimo_pedido', models.DateField(help_text='Fecha del ultimo pedido al proveedor', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(help_text='proveedor de la compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='compras.Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(help_text='usuario que registro la compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='personas.Persona'),
        ),
    ]
