# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20171020_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='precio',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Precio unitario del producto', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto total de la compra', max_digits=16, null=True),
        ),
    ]
