# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20171022_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='procesada',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad_procesada',
            field=models.FloatField(default=0, help_text='cantidad de procesada'),
        ),
    ]
