# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del almacen', max_length=30)),
                ('direccion', models.CharField(help_text='direccion del almacen', max_length=60)),
                ('telefono', models.CharField(help_text='telefono de comunicacion', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del almacen', max_length=30)),
                ('capacidad_total', models.FloatField(default=0, help_text='capacidad del almacen')),
                ('capacidad_restante', models.FloatField(help_text='capacidad disponible en el almacen')),
                ('almacen', models.ForeignKey(help_text='Almacen al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='ubicacion.Almacen')),
            ],
        ),
    ]
