# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='eliminable',
            field=models.BooleanField(default=True),
        ),
    ]
