# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20171020_0637'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='codigo unico de la unidad', max_length=30)),
                ('estado', models.BooleanField(default=True, help_text='Disponible/Usado')),
                ('estante', models.ForeignKey(help_text='Estante donde se ubicará la unidad', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='ubicacion.Estante')),
                ('unidad', models.ForeignKey(help_text='producto a ubicar', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='compras.DetalleCompra')),
            ],
        ),
    ]
