# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(help_text='codigo del almacen', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='codigo',
            field=models.CharField(help_text='codigo unico de la unidad', max_length=64, unique=True),
        ),
    ]
