# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_auto_20171111_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion',
            old_name='ancho',
            new_name='anchura',
        ),
    ]
