# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0004_auto_20171022_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='codigo',
            field=models.CharField(help_text='codigo unico de la unidad', max_length=64),
        ),
    ]
