# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0005_auto_20171022_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='fecha',
            field=models.DateField(help_text='Fecha de la ingreso', null=True),
        ),
    ]
