# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_auto_20171012_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(help_text='Rif/CI del cliente', max_length=15)),
                ('nombre', models.CharField(help_text='Nomrbe del cliente', max_length=30)),
                ('telefono', models.CharField(help_text='Telefono del cliente', max_length=15, null=True)),
                ('direccion', models.CharField(help_text='Direccion del cliente', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='cantidad de salida')),
                ('fecha', models.DateField(help_text='Fecha de la compra', null=True)),
                ('producto', models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='codigo de la venta', max_length=30, unique=True)),
                ('total', models.FloatField(default=0, help_text='Monto total de la venta', null=True)),
                ('fecha', models.DateField(help_text='Fecha de la venta')),
                ('cliente', models.ForeignKey(help_text='cliente de la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(help_text='venta a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.Venta'),
        ),
    ]
